import=[
  "$HOME/.config/helix/vim.toml"
]

theme = "dark_plus"

[editor]
mouse = true
auto-format = true
auto-save = true
color-modes = true
true-color = true
shell = ["fish", "-c"]
scrolloff = 8
line-number = "relative"
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner", "version-control", "workspace-diagnostics"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
